version: "3"
services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/db
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/daweb/server/
    working_dir: /daweb/server/
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "35432:5432"
